# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Documents/maya/2020/prefs/scripts/junkbox/python/junkbox/ui/assetviewwidget.ui'
#
# Created: Thu Feb 18 14:10:34 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_assetViewWidget(object):
    def setupUi(self, assetViewWidget):
        assetViewWidget.setObjectName("assetViewWidget")
        assetViewWidget.resize(867, 348)
        self.verticalLayout = QtWidgets.QVBoxLayout(assetViewWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.collectionLabel = QtWidgets.QLabel(assetViewWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.collectionLabel.setFont(font)
        self.collectionLabel.setObjectName("collectionLabel")
        self.horizontalLayout_2.addWidget(self.collectionLabel)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.itemCountLabel = QtWidgets.QLabel(assetViewWidget)
        self.itemCountLabel.setObjectName("itemCountLabel")
        self.horizontalLayout_2.addWidget(self.itemCountLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.thumbnailSizeSlider = QtWidgets.QSlider(assetViewWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnailSizeSlider.sizePolicy().hasHeightForWidth())
        self.thumbnailSizeSlider.setSizePolicy(sizePolicy)
        self.thumbnailSizeSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.thumbnailSizeSlider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.thumbnailSizeSlider.setMinimum(50)
        self.thumbnailSizeSlider.setMaximum(200)
        self.thumbnailSizeSlider.setProperty("value", 150)
        self.thumbnailSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thumbnailSizeSlider.setObjectName("thumbnailSizeSlider")
        self.horizontalLayout_2.addWidget(self.thumbnailSizeSlider)
        self.styleViewButton = FlatButton(assetViewWidget)
        self.styleViewButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/listView.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.styleViewButton.setIcon(icon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/thumbnailView.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.styleViewButton.setProperty("icon1", icon1)
        self.styleViewButton.setObjectName("styleViewButton")
        self.horizontalLayout_2.addWidget(self.styleViewButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.changeCollectionButton = FlatButton(assetViewWidget)
        self.changeCollectionButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/changeCollection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changeCollectionButton.setIcon(icon2)
        self.changeCollectionButton.setObjectName("changeCollectionButton")
        self.horizontalLayout_3.addWidget(self.changeCollectionButton)
        self.removeButton = FlatButton(assetViewWidget)
        self.removeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon3)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_3.addWidget(self.removeButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.searchEdit = QtWidgets.QLineEdit(assetViewWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchEdit.sizePolicy().hasHeightForWidth())
        self.searchEdit.setSizePolicy(sizePolicy)
        self.searchEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.searchEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_2.addWidget(self.searchEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.thumbnailViewWidget = QtWidgets.QListWidget(assetViewWidget)
        self.thumbnailViewWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.thumbnailViewWidget.setMovement(QtWidgets.QListView.Static)
        self.thumbnailViewWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.thumbnailViewWidget.setSpacing(10)
        self.thumbnailViewWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.thumbnailViewWidget.setWordWrap(True)
        self.thumbnailViewWidget.setObjectName("thumbnailViewWidget")
        self.horizontalLayout.addWidget(self.thumbnailViewWidget)
        self.listViewWidget = QtWidgets.QTreeWidget(assetViewWidget)
        self.listViewWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listViewWidget.setIndentation(0)
        self.listViewWidget.setRootIsDecorated(False)
        self.listViewWidget.setExpandsOnDoubleClick(False)
        self.listViewWidget.setObjectName("listViewWidget")
        self.horizontalLayout.addWidget(self.listViewWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(assetViewWidget)
        QtCore.QMetaObject.connectSlotsByName(assetViewWidget)

    def retranslateUi(self, assetViewWidget):
        assetViewWidget.setWindowTitle(QtWidgets.QApplication.translate("assetViewWidget", "Form", None, -1))
        self.collectionLabel.setText(QtWidgets.QApplication.translate("assetViewWidget", "CollectionName", None, -1))
        self.itemCountLabel.setText(QtWidgets.QApplication.translate("assetViewWidget", "x assets", None, -1))
        self.changeCollectionButton.setToolTip(QtWidgets.QApplication.translate("assetViewWidget", "move the asset to another collection", None, -1))
        self.removeButton.setToolTip(QtWidgets.QApplication.translate("assetViewWidget", "remove the asset", None, -1))
        self.searchEdit.setPlaceholderText(QtWidgets.QApplication.translate("assetViewWidget", "Search ...", None, -1))
        self.listViewWidget.setSortingEnabled(True)
        self.listViewWidget.headerItem().setText(0, QtWidgets.QApplication.translate("assetViewWidget", "     Name", None, -1))
        self.listViewWidget.headerItem().setText(1, QtWidgets.QApplication.translate("assetViewWidget", "Size", None, -1))
        self.listViewWidget.headerItem().setText(2, QtWidgets.QApplication.translate("assetViewWidget", "Type", None, -1))
        self.listViewWidget.headerItem().setText(3, QtWidgets.QApplication.translate("assetViewWidget", "Last Modified", None, -1))

from junkbox.component.flatbutton import FlatButton
from junkbox.resource import resource_rc
